//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturahasproducto
    {
        public int id { get; set; }
        public Nullable<int> factura_id { get; set; }
        public Nullable<int> producto_id { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public Nullable<decimal> @base { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> valor_iva { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> valor_descuento { get; set; }
        public Nullable<decimal> precio_total { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producto producto { get; set; }
    }
}
